replicaCount: 2

image:
  repository: eeshulu/n01731657-nginx-app
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "nginx-app"

service:
  type: NodePort
  port: 80
  nodePort: 30080

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: n01731657.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
